### ISSUE TITLE
Pelican driver does not detect disconnected state

### ISSUE THREAD

**Issue by gtfierro** [SoftwareDefinedBuildings/bw2-contrib#18]
Pelican driver reports the last known values of the thermostat, even when the thermostat is disconnected from the gateway. This requires some investigation into the Pelican API to see how best to detect this; its my hunch that the API reports the last known value by default.

**Comment by gtfierro** [comment]
@jhkolb any progress on this?

**Comment by jhkolb** [comment]
Delegated this to one the work studies, who has pretty good knowledge of the Pelican API and driver. We have two leads at this point:
  * Using the `history` endpoint on the Pelican API to fetch timestamped data. Remains to be seen if these timestamps accurately reflect the age of the latest reading
  * Further investigating the web interface of Pelican's cloud service to see how they know if a thermostat is disconnected

**Comment by john-b-yang** [comment]
@gtfierro @jhkolb Glad to report that there is a resolution to the problem above. Within the "ThermostatHistory" object described in the API, the "timestamp" field reports the time when the last known value was recorded from the thermostat. When the thermostat is disconnected, the lack of more recent timestamps since the disconnect is an indication of the problem.

The only issue with this approach is that the API does not handle time zones. Specifically, there is no universal clock that all the thermostats are synced to. The API requires the user to define the timezone that the Pelican is in, and it does not handle converting from one timezone to another implicitly. As a result, we have to be aware of the user's timezone in order to report the "timestamp" field properly.

An alternative approach I'm exploring right now is toggling the "NotificationUnreachable" field in the "Thermostat" object. The field states that the thermostat will send a "notification" when it becomes unreachable. The only issue is that I'm not sure what "notification" exactly is (email? text msg?), so, by using the web portal, I'm currently trying to figure out how exactly that notification is communicated.

**Comment by gtfierro** [comment]
Hey @john-b-yang 

What format is the timestamp in? can you provide an example?

The pelican platform does send emails for some failure cases (such as a thermostat not reaching temperature by a scheduled time), so I'm guessing that toggling that field means that it will send emails also when the thermostats are disconnected/unreachable. This *might* be exposed somewhere in the HTML somewhere. Have you tried experimenting with the Pelican that's in 410?

**Comment by jhkolb** [comment]
According to the documentation, the timestamps are ISO 8601. However, what @john-b-yang has observed is that the API doesn't respect the timezones of the timestamps submitted as query parameters.

For example, when requesting data between now and two hours ago using UTC timestamps, the Pelican API just assumes the timestamps are in the same timezone as the thermostat you're asking about. If that's PDT, then you won't get any data back at all, because those time bounds are thought to be in the future (since PDT is UTC - 7).

Similarly, all timestamps contained in results returned by the API omit timezone information and are expressed in the thermostat's notion of local time.

Unfortunately, it seems we'll need to know which timezone the thermostat has been configured to use in order to reason about its timestamps, and this isn't something we can determine through the API.

**Comment by gtfierro** [comment]
Ah, okay that makes sense. Could we possibly provide the timezone as a configuration option for the thermostat? Would that make using the timestamps a feasible option?

**Comment by jhkolb** [comment]
Yeah, that solution would work and it's what we were thinking as well. How onerous would it be to add a field to the Pelican configuration for an IANA timezone? And would we want to default to `America/Los_Angeles`?

**Comment by gtfierro** [comment]
That should be pretty easy to add. The trickiest part I imagine will be in figuring out the correct invocation to interpret the timestamp that's retrieved from the API. @john-b-yang do you have enough to get started? If I'm understanding the issue with the API, then you should be able to use [ParseInLocation](https://golang.org/pkg/time/#ParseInLocation)

**Comment by john-b-yang** [comment]
@gtfierro That makes sense, I can begin making edits. Personally, I think a convenient way to implement the solution above is to add the location as a parameter in the "params.yml" file that Spawnpoint uses to configure the driver.

How would you like me to make the edits? I can create a branch of this repository and then make a pull request?

**Comment by gtfierro** [comment]
Having it in the `params.yml` file and then submitting through a PR would be perfect. Thanks!

**Comment by john-b-yang** [comment]
👍🏼 Will get to it.

**Comment by john-b-yang** [comment]
Submitted Pull Request!

**Comment by gtfierro** [comment]
Addressed in https://github.com/SoftwareDefinedBuildings/bw2-contrib/pull/23
